# Bio-Inspired Algorithms
## 2-D Genetic Algorithm

### Dr. Carlos Lopez-Franco @ UDG
### Dariana Gomez-Alvarez

Objective Function
$$ f(x,y) = x^2 + y^2 $$

## Libraries

In [1]:
import numpy as np

## Main

In [21]:
################### Initial Parameters ########################

pop = np.array([
    [1, 0, 0, 1, 0, 1, 1, 1],
    [0, 1, 0, 1, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 1, 1, 1],
    [0, 0, 1, 1, 1, 1, 0, 1],
    [0, 1, 1, 1, 1, 1, 0, 1]
    ])


l_sel= [[0, 2, 3], [3, 0, 5], [0, 1, 2], [0, 5, 1], [1, 5, 4], [5, 1, 4], 
        [2, 4, 0], [4, 2, 3], [1, 2, 0], [1, 0, 4], [1, 2, 3], [5, 4, 1], 
        [4, 2, 5], [3, 4, 0], [0, 2, 5], [1, 4, 0], [0, 1, 4], [4, 2, 3], 
        [4, 1, 2], [1, 4, 2], [5, 3, 1], [1, 2, 4], [0, 1, 3], [2, 0, 4], 
        [0, 2, 4], [0, 1, 5], [3, 0, 4], [1, 3, 4], [2, 4, 0], [2, 4, 3],
        [2, 3, 5], [2, 4, 5], [0, 4, 1], [4, 0, 5], [3, 1, 5], [0, 5, 4], 
        [4, 1, 0], [3, 4, 0], [1, 4, 2], [5, 4, 3], [0, 1, 5], [0, 2, 1], 
        [2, 1, 3], [2, 5, 3], [3, 5, 1], [3, 0, 1], [4, 3, 1], [1, 5, 4], 
        [1, 5, 2], [4, 2, 3], [1, 5, 4], [0, 1, 2], [5, 2, 1], [5, 0, 4]]

l_rand= [0.22, 0.55, 0.03, 0.30, 0.06, 0.77, 0.67, 0.47, 0.59, 
         0.87, 0.42, 0.48, 0.26, 0.49, 0.35, 0.45, 0.99, 
         0.80, 0.56, 0.17, 0.01, 0.02, 0.35, 0.50, 0.22, 0.94,
         0.78, 0.87, 0.99, 0.36, 0.52, 0.87, 0.60, 0.37,
         0.03, 0.81, 0.54, 0.63, 0.60, 0.10, 0.66, 0.65, 0.98,
         0.12, 0.69, 0.48, 0.36, 0.78, 0.81, 0.37, 0.19, 
         0.87, 0.45, 0.21, 0.72, 0.37, 0.41, 0.53, 0.35, 0.70, 
         0.29, 0.29, 0.12, 0.31, 0.97, 0.02, 0.71, 0.73,
         0.37, 0.67, 0.62, 0.78, 0.74, 0.19, 0.42, 0.40, 0.43, 
         0.64, 0.38, 0.65, 0.21, 0.49, 0.49, 0.60, 0.22, 
         0.38, 0.03, 0.74, 0.18, 0.48, 0.14, 0.76, 0.23, 0.31, 
         0.63, 0.12, 0.89, 0.30, 0.19, 0.82, 0.08, 0.07, 
         0.94, 0.48, 0.13, 0.65, 0.11, 0.69, 0.82, 0.98, 0.01, 
         0.91, 0.28, 0.40, 0.56, 0.13, 0.89, 0.68, 0.08, 
         0.07, 0.43, 0.51, 0.50, 0.72, 1.00, 0.72, 0.47, 0.86, 
         0.94, 0.62, 0.76, 0.84, 0.74, 0.10, 0.32, 0.45, 
         0.51, 0.27, 0.17, 0.41, 0.17, 0.04, 0.32, 0.08, 0.54,
         0.58, 0.44, 0.86, 0.61, 0.01, 0.78, 0.50, 0.31,
         0.45, 0.25, 0.88, 0.50, 0.26, 0.13, 0.04, 0.05, 0.25, 
         0.94, 0.07, 0.30, 0.90, 0.68, 0.07, 0.55, 0.05, 
         0.71, 0.70, 0.78, 1.00, 0.43, 0.63, 0.10, 0.47, 0.41,
         0.54, 0.12, 0.29, 0.12, 0.13, 0.85, 0.51, 0.36,
         0.37, 0.71, 0.64, 0.09, 0.52, 0.45, 0.42, 0.44, 0.71, 
         0.63, 0.19, 0.89, 0.40, 0.01, 0.64, 0.63, 0.78, 
         0.81, 0.42, 0.72, 0.35, 0.24, 0.33, 0.42, 0.64, 0.49,
         0.87, 0.36, 0.85, 0.05, 0.51, 0.01, 0.72, 0.20, 
         0.33, 0.66, 0.91, 0.55, 0.66, 0.61, 0.56, 0.83, 0.05, 
         1.00, 0.90, 0.30, 0.03, 0.26, 0.39, 0.22, 0.88, 
         0.26, 0.10, 0.38, 0.31, 1.00, 0.12, 0.13, 0.58, 0.99, 
         0.30, 0.03, 0.78, 0.60, 0.99, 0.18, 0.96, 0.88, ]

ind_size = 8
inds_per_gen = 6

cr_valid, mu_valid = sep_cross_mut(l_rand)


l_cross= [3, 2, 6, 4, 1, 2, 1, 1, 1, 1, 3, 5, 2, 3]

ran_min = -1
ran_max = 1

r_cross = 0.9
r_mut = 0.25

best_fitness = 1000

x_values_bin, y_values_bin = split_population(pop)

################ Objective Function #######################

obj_function = lambda x, y: x**2 + y**2


######################## Iterations ###############################

for gen in range(9):
    #print("Gen", gen)
        
    combined_array = np.hstack((x_values_bin, y_values_bin))
    #print(combined_array)  
    
    x, y = binary_population_to_decoded_values(x_values_bin, y_values_bin, ran_min, ran_max)
    
    x_values = np.array(x)
    y_values = np.array(y)

    #print(x_values,y_values)
    ####################### Fitnesses #######################
    fitnesses = np.array([])
    
    fitnesses = np.array(obj_function(x_values, y_values))
    
    ##################### Tournament #########################

    champs = tournament(gen, l_sel, fitnesses)

    #print(f"The champions of generation {gen} are: {champs}")
    
    fit_dict = {index: value for index, value in enumerate(fitnesses)} 
        
    subtourns = champs_fcn(champs)
    
    best_fitness = min(champs)
        
    ############## Creating new generation #################
    new_x_list = []
    new_y_list = []
    
    for item in subtourns:
        new_x_list.append(x_values_bin[item])
        new_y_list.append(y_values_bin[item])

    x_values_bin = np.array(new_x_list)
    y_values_bin = np.array(new_y_list)

       
    ################## Crossover #####################
    if cr_valid[0] < r_cross:
        #print("crosses", cr_valid[0])
        x_values_bin, y_values_bin = crossover(x_values_bin, y_values_bin, l_cross[gen])
        cr_valid = cr_valid[1:]
    else:
        #print("doesnt cross")
        pass
    
        
    ################# Mutation #######################
    position = 0
    for mutating in range(ind_size*3):
        if mu_valid[0] < r_mut:
            #print(mutating, ": mutates",position, mu_valid[0])
            x_values_bin, y_values_bin = mutation(x_values_bin, y_values_bin, position)
            mu_valid = mu_valid[1:]
        else:
            #print(mutating, ": doesnt mutate",position, mu_valid[0])
            mu_valid = mu_valid[1:]
            position += 1
        if position > 7:
            position = 0
            
    if best_fitness < 0.01:
        print('*'*100)
        print(f"Fittest individual found. Fitness: {best_fitness} in Gen {gen}.\n",combined_array)
        print('*'*100)

        break

****************************************************************************************************
Fittest individual found. Fitness: 0.008888888888888885 in Gen 2.
 [[1 0 1 0 1 0 1 0]
 [0 1 1 1 0 1 1 1]
 [0 1 1 1 0 1 1 1]
 [0 1 1 1 0 1 1 1]
 [0 1 1 1 0 1 1 1]
 [1 0 1 0 0 1 1 1]]
****************************************************************************************************


## Functions Definitions

In [3]:
def split_population(population):
    # Split each row into two arrays of shape (6, 4) for x and y
    x_array = population[:, :4]
    y_array = population[:, 4:]
    return x_array, y_array

In [4]:
def binary_population_to_decoded_values(x, y, min_value, max_value):
    decoded_x = []
    decoded_y = []
    bits_per_individual = 4  # It's actually 8, but we are working separately
    
    #print(x,y)

    for row_x, row_y in zip(x, y):
        binary_x = "".join(map(str, row_x))
        binary_y = "".join(map(str, row_y))

        decimal_x = int(binary_x, 2)
        decimal_y = int(binary_y, 2)

        decoded_x_value = min_value + decimal_x * (max_value - min_value) / (2 ** bits_per_individual - 1)
        decoded_y_value = min_value + decimal_y * (max_value - min_value) / (2 ** bits_per_individual - 1)

        decoded_x.append(decoded_x_value)
        decoded_y.append(decoded_y_value)

    #print(decoded_x, decoded_y)
    
    return decoded_x, decoded_y

In [5]:
def tournament(generation, selection, fitnesses): 
    # Separate tournaments' list into smaller lists (same amount as individuals in initial population)

    n = 6 # Number of elements per smaller list

    tournaments= []

    smaller_lists = [selection[i:i + n] for i in range(0, len(selection), n)]

    for sublist in smaller_lists:
        tournaments.append(sublist)
        
    sorted_list = []
    comps = 3 # competitors per tournament
    
    # actual tournament process
    
    champs = []
    
    for tourns in tournaments[generation]:
        for competitor in tourns:
            sorted_list.append(fitnesses[competitor])
    smaller_tourns = [sorted_list[i:i + comps] for i in range(0, len(sorted_list), comps)]
    for element in smaller_tourns:
        champs.append(min(element))
        
    return champs

In [6]:
def champs_fcn(champions):
    # Retrieve indices to know which individuals will integrate new population

    indices = [key for value in champions for key, dict_value in fit_dict.items() if value == dict_value]
    subtourns_ = [indices[i:i+6] for i in range(0, len(indices), 6)]

    subtourns = subtourns_[0]
    
    return subtourns


In [7]:
def sep_cross_mut(list_randoms):
    # Separate items in l_rand list so that we have separate lists for crossover and mutation (for now).
    pos = ind_size*2 + 1
    
    c_val = list_randoms[::pos]

    m_val = []

    for i in range(1, len(list_randoms), 1):
        if i % pos != 0:
            m_val.append(list_randoms[i])
            
    cross_valid = np.array(c_val)
    mut_valid = np.array(m_val)
            
    return cross_valid, mut_valid

In [8]:
def crossover(x4cross, y4cross, bit):
    for t in range(5):
        if bit < 4:
            # Swap bits in x4cross and y4cross
            tmp = x4cross[t][bit]
            #print("current bit:", tmp)
            x4cross[t][bit] = x4cross[t][bit]
            x4cross[t][bit] = tmp
        else:
            bit -= 4  # Move to the next 4 bits
            # Swap bits in x4cross and y4cross
            tmp = y4cross[t][bit]
            y4cross[t][bit] = y4cross[t][bit]
            y4cross[t][bit] = tmp
    return x4cross, y4cross


In [9]:
def mutation(x4mut, y4mut, ind):
    for t in range(5):
        if ind < 4:
            x4mut[t][ind] = 1 - x4mut[t][ind]
        else:
            ind -= 4
            y4mut[t][ind] = 1 - y4mut[t][ind]
        
    return x4mut, y4mut